### ISSUE TITLE
번역 기여 관련

### ISSUE THREAD

**Issue by icepeng** [ragubyun/javascript-testing-best-practices#3]
https://github.com/icepeng/javascript-testing-best-practices/blob/master/readme.kr.md

8월중 1.9까지 번역을 진행하다가 동기가 저하되어서 중단했다가 다시 진행하려는 차에 발견하여 이슈를 남깁니다.

번역 진행중이신 섹션을 알려주시면 나머지 부분을 우선적으로 번역해보려 하는데, 의견 남겨주시면 감사하겠습니다.

**Comment by ragubyun** [comment]
제안 감사드립니다.

현재 섹션 3, 4 진행중이니 섹션 5 하시면서 중간중간 PR 주시면 머지하겠습니다.
